name: Test with Docker

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Preprocess Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t tsmip .

      - name: Test with Docker
        run: docker run tsmip pytest